### ISSUE TITLE
Add collaborator access

### ISSUE THREAD

**Issue by jhabdas** [hillockink/hexotemp1#1]
HI Mathias. Port is finished. Took me just over 4 hours. It looks pretty amazing, and I got a good look at the quality content of your site. I can sub a pull request with the changes but **need collaborator access to this repo**.

Your new site builds in `38ms`, and incorporates all of the latest features from [After Dark](https://comfusion.github.io/after-dark/), including image lazyloading and boss SEO.

<img width="375" alt="screen shot 2017-02-15 at 9 53 15 pm" src="https://cloud.githubusercontent.com/assets/440298/22977501/c63f8222-f3c9-11e6-9376-4391be22a05f.png">

**Comment by jhabdas** [comment]
Thanks! Will push up tomorrow and look for feedback.

**Comment by hillockink** [comment]
Thanks!
